import type { Field } from "./types";
import {
  LISTING_CARD_GAP,
  LISTING_CARD_RADIUS,
  LISTING_CARD_SIZE,
  LISTING_CATEGORY_LIMIT,
  LISTING_CATEGORY_STYLES,
  LISTING_COVER_HEIGHT,
  LISTING_COVER_OVERLAY,
  LISTING_COVER_RADIUS,
  LISTING_COVER_SCOPES,
  LISTING_COVER_WIDTHS,
  LISTING_FEATURED_OPTIONS,
  LISTING_FILTER_LAYOUTS,
  LISTING_BREADCRUMB_ALIGNS,
  LISTING_PAGINATIONS,
  LISTING_TITLE_ALIGNS,
} from "./products-listing-layout";
import { FEATURED_CATEGORIES_SOURCES } from "@/lib/site-config/home-page-config";

/**
 * The products listing's page-design settings, in inspector order: title,
 * filters, categories, cover. Defaults mirror `readProductsListingLayout`,
 * which is what the storefront actually reads — these only draw the editor
 * and validate the document on save.
 */
const CATEGORY_DESIGNS = LISTING_CATEGORY_STYLES.filter((style) => style !== "hidden");

export const PRODUCTS_LISTING_FIELDS: Field[] = [
  {
    key: "titleAlign",
    type: "select",
    options: LISTING_TITLE_ALIGNS,
    default: "theme",
    width: "half",
  },
  {
    key: "breadcrumbAlign",
    type: "select",
    options: LISTING_BREADCRUMB_ALIGNS,
    default: "theme",
    width: "half",
    hint: "Follows the title unless you set it here.",
  },
  {
    key: "filterLayout",
    type: "select",
    options: LISTING_FILTER_LAYOUTS,
    default: "sidebar",
    width: "half",
    hint: "Vertical lists filters down the left. Horizontal puts them in a row above the products, as boxes or as dropdowns; Filter button gathers them into one panel. Phones always use the filter sheet.",
  },
  {
    key: "featuredProducts",
    type: "select",
    options: LISTING_FEATURED_OPTIONS,
    default: "theme",
    width: "half",
    showWhen: { key: "filterLayout", values: ["sidebar"] },
    hint: "A short list of featured products under the filters.",
  },
  {
    key: "pagination",
    type: "select",
    options: LISTING_PAGINATIONS,
    default: "theme",
    width: "half",
    hint: "Numbered pages, or more products as the shopper scrolls.",
  },
  {
    key: "categoryStyle",
    type: "select",
    options: LISTING_CATEGORY_STYLES,
    default: "hidden",
    width: "half",
    hint: "The same designs as the Categories section. Every one filters this page. Chips sit in a row above the products.",
  },
  {
    key: "categoryAlign",
    type: "select",
    options: ["left", "center"],
    default: "left",
    width: "third",
    showWhen: { key: "categoryStyle", values: CATEGORY_DESIGNS },
  },
  {
    key: "categorySource",
    type: "select",
    options: FEATURED_CATEGORIES_SOURCES,
    default: "topLevel",
    width: "third",
    showWhen: { key: "categoryStyle", values: CATEGORY_DESIGNS },
  },
  {
    key: "categoryLimit",
    type: "number",
    default: LISTING_CATEGORY_LIMIT.default,
    min: LISTING_CATEGORY_LIMIT.min,
    max: LISTING_CATEGORY_LIMIT.max,
    width: "third",
    showWhen: { key: "categoryStyle", values: CATEGORY_DESIGNS },
  },
  // The cards design's own geometry. Circles and overlay are shape-defined
  // designs — a radius on a circle does nothing and a size would stop them
  // matching the Categories section — so these three follow cards alone.
  {
    key: "categoryRadius",
    type: "number",
    default: LISTING_CARD_RADIUS.default,
    min: LISTING_CARD_RADIUS.min,
    max: LISTING_CARD_RADIUS.max,
    width: "third",
    showWhen: { key: "categoryStyle", values: ["cards"] },
  },
  {
    key: "categorySize",
    type: "number",
    default: LISTING_CARD_SIZE.default,
    min: LISTING_CARD_SIZE.min,
    max: LISTING_CARD_SIZE.max,
    width: "third",
    showWhen: { key: "categoryStyle", values: ["cards"] },
    hint: "Card width in pixels; 0 fits them to the row.",
  },
  {
    key: "categoryGap",
    type: "number",
    default: LISTING_CARD_GAP.default,
    min: LISTING_CARD_GAP.min,
    max: LISTING_CARD_GAP.max,
    width: "third",
    showWhen: { key: "categoryStyle", values: ["cards"] },
    hint: "Between the cards, in pixels. Phones use half.",
  },
  {
    key: "categoryIds",
    type: "categoryList",
    showWhen: { key: "categorySource", values: ["manual"] },
  },
  {
    key: "coverSlider",
    type: "slider",
    default: "",
    width: "half",
    hint: "A saved slider as a banner above the title. Its width and corners follow the cover settings; its height the cover height, or the slider's own.",
  },
  {
    key: "cover",
    type: "background",
    width: "half",
    video: true,
    hint: "Painted behind the page title — a colour, a gradient, a picture or a video. Leave empty for no cover.",
  },
  {
    key: "coverWidth",
    type: "select",
    options: LISTING_COVER_WIDTHS,
    default: "contained",
    width: "half",
  },
  {
    key: "coverScope",
    type: "select",
    options: LISTING_COVER_SCOPES,
    default: "coverTitleCategories",
    width: "half",
    hint: "Chips always stay in the toolbar.",
  },
  {
    key: "coverText",
    type: "color",
    default: "",
    width: "half",
    hint: "Empty picks black or white for contrast.",
  },
  {
    key: "coverHeight",
    type: "number",
    default: LISTING_COVER_HEIGHT.default,
    min: LISTING_COVER_HEIGHT.min,
    max: LISTING_COVER_HEIGHT.max,
    width: "third",
    hint: "Minimum height in pixels; 0 fits the content.",
  },
  {
    key: "coverRadius",
    type: "number",
    default: LISTING_COVER_RADIUS.default,
    min: LISTING_COVER_RADIUS.min,
    max: LISTING_COVER_RADIUS.max,
    width: "third",
    showWhen: { key: "coverWidth", values: ["contained"] },
  },
  {
    key: "coverOverlay",
    type: "number",
    default: LISTING_COVER_OVERLAY.default,
    min: LISTING_COVER_OVERLAY.min,
    max: LISTING_COVER_OVERLAY.max,
    width: "third",
    hint: "Darkens an image cover, in percent.",
  },
  {
    key: "coverBreadcrumb",
    type: "toggle",
    default: true,
    hint: "Moves the breadcrumb inside the cover.",
  },
];
